### ISSUE TITLE
create gazebo-model branch

### ISSUE THREAD

**Issue by lrapetti** [robotology-playground/human-gazebo#1]
In the `master` branch, 8 new `urdfs` models have been uploaded and old model have ben deleted.
However, those `urdfs` currently don't have the configuration for `yarp` and `gazebo`, for this reason I have created a new branch [`gazebo-model`](https://github.com/robotology-playground/human-gazebo/tree/gazebo-model) with the old model and its configuration files.

**Comment by yeshasvitirupachuri** [comment]
The old files related to the initial investigation on using human models in gazebo are put in the [legacy](https://github.com/robotology-playground/human-gazebo/tree/master/legacy) directory.

**Comment by yeshasvitirupachuri** [comment]
Ideally, we can have a single `conf` directory that contains the motor control board configurations for the human. Additionally, we can also add other sensors like FT if needed. Also, we can have a [shell-scripts](https://github.com/robotology-playground/human-gazebo/tree/gazebo-model/scripts) directory that contains the scripts to use plugins like `linkattacher` in case of setting up pHRI experiments in gazebo simulation like standup or collaborative lifting.

**Comment by lrapetti** [comment]
> The old files related to the initial investigation on using human models in gazebo are put in the [legacy](https://github.com/robotology-playground/human-gazebo/tree/master/legacy) directory.

my bad, I missed that folder. I'm going to remove the branch.
