### ISSUE TITLE
urdf gazebo simulation : fake links

### ISSUE THREAD

**Issue by jtia** [robotology-playground/human-gazebo#10]
Hello,

For each "Subject", you specify in the urdf this :

`<!--To open this model with Gazebo replace the null masses, inertias and dimensions of the 'fake links f1 and f2'-->`

I'm sorry if it's already specified somewhere but please, can you tell me why theses fake links? and what are the correct values to put? If you have an urdf filled with the correct values ​​and you agree to transmit it to me, you would be of great help to me :)

Regards

**Comment by lrapetti** [comment]
> I'm sorry if it's already specified somewhere but please, can you tell me why theses fake links? 

The purpose of those fake links is to simulate spherical joints by combining three revolute joints:
`link_A>spherical_joint>link_B` -> `link_A>revolute>fake_link>revolute>fake_link>revolute>link_B`

> and what are the correct values to put? If you have an urdf filled with the correct values ​​and you agree to transmit it to me, you would be of great help to me :)

Being those link only for kinematic modelling purpose there is no "correct value", but any small value, being negligible w.r.t. other links of the model, should be fine (e.g. with 3 order of magnitude smaller should be enough).
Maybe @Yeshasvitvs can provide you with some example.

**Comment by yeshasvitirupachuri** [comment]
@jtia as Lorenzo highlighted, the fake links are a mere convenience to achieve a spherical joint. These urdf files can be used without any problems for kinematic visualization using tools like Rviz. However, if you are planning to use these files for dynamics simulation using tools like Gazebo, the small values may cause problems and you need to increase them

**Comment by yeshasvitirupachuri** [comment]
@jtia if your doubt is clear, can we close this issue ? Thanks.

**Comment by jtia** [comment]
Hello, thanks for your reply. It's ok for me.
