### ISSUE TITLE
Failure to spawn full human model in gazebo

### ISSUE THREAD

**Issue by s-arora1987** [robotology-playground/human-gazebo#2]
I cloned the "human-gazebo" repo, and tried to spawn the urdfs using
 
  <node name="spawn_human" pkg="gazebo_ros" type="spawn_model"
        args="-file $(path-to-urdf) -urdf -model XSensStyleModel_template
    -x 0.0
    -y 0.0
    -z 1.0"/>

Gazebo showed a white box instead of a human body. Could you please tell me how to fix this issue?

**Comment by yeshasvitirupachuri** [comment]
@s-arora-1987 at the moment the only working model for gazebo is inside [legacy](https://github.com/robotology-playground/human-gazebo/tree/master/legacy) directory [sub0](https://github.com/robotology-playground/human-gazebo/tree/master/legacy/sub0) model. To successfully spawn this human model in gazebo you need to add the legacy directory (which contains gazebo [database](https://github.com/robotology-playground/human-gazebo/blob/master/legacy/database.config) configuration file) i.e `export GAZEBO_MODEL_PATH=/<your-path>/legacy`

**Comment by s-arora1987** [comment]
Are there wrist joint and fingers to pick and rotate objects?

**Comment by yeshasvitirupachuri** [comment]
Unfortunately not yet. I suggest to take a look at `icub-gazebo` repository for a robot with hands including fingers that are similar to a human being.

**Comment by yeshasvitirupachuri** [comment]
Closing this issue and a proper readme file will be added #3 to provide the basic details what this repository offers.
