### ISSUE TITLE
Remove the joint limits for 48DOF human models

### ISSUE THREAD

**Issue by kouroshD** [robotology-playground/human-gazebo#21]
Following the investigation during risk assessment sprint, thanks to @lrapetti  insights, we noticed the base vs human configuration mismatch is due to the human joint limits in 48 DOFs. The idea is to remove those limits similar to 66DOF models.
cc @Yeshasvitvs

**Comment by kouroshD** [comment]
@Yeshasvitvs  @lrapetti  I do not have access to add it to milestone and assign it! Feel free to do it.

**Comment by kouroshD** [comment]
At the moment with consideration of the joint limits the results are like:

https://user-images.githubusercontent.com/17707730/116062063-dafef280-a683-11eb-94bd-57ef56d3a5f6.mp4


When we remove the joint limits, the results is shown in the following


https://user-images.githubusercontent.com/17707730/116062121-ea7e3b80-a683-11eb-8530-2494530fc89a.mp4

**Comment by kouroshD** [comment]
Similar to 66 DOF models, https://github.com/robotology/human-gazebo/blob/6dd5aabfbfe105896af6ccad490f147122214617/humanSubject01/humanSubject01_66dof.urdf#L926
I will put `+10 rad` and `- 10 rad` as the joint limits for all the 48 DOF models.

**Comment by kouroshD** [comment]
Related PR https://github.com/robotology/human-gazebo/pull/22

I have tested for the lifting task and the visualization for all the models were as expected.

**Comment by claudia-lat** [comment]
May we close this issue @kouroshD?

**Comment by lrapetti** [comment]
Done in https://github.com/robotology/human-gazebo/pull/22
