### ISSUE TITLE
Generate models with 48DoFs

### ISSUE THREAD

**Issue by lrapetti** [robotology-playground/human-gazebo#4]
At the moment this repo contains only the models generated with 66DoFs. It would be useful to have also the same model with 48DoFs.

@claudia-lat @Yeshasvitvs

**Comment by claudia-lat** [comment]
Just added the 48dof models. 
@lrapetti @Yeshasvitvs

**Comment by lrapetti** [comment]
Thanks @claudia-lat,
I have also update the `CMakeLists` to install the new models https://github.com/robotology-playground/human-gazebo/commit/402249d3e59c607c282b62e218550edf854633fd
