### ISSUE TITLE
Move human-gazebo repo to robotology

### ISSUE THREAD

**Issue by kouroshD** [robotology-playground/human-gazebo#5]
While working with HDE, and try to test with human models, I noticed I do not have the default human models stated in xml files.
Therefore, HDE implicitly has dependency to this repo. I suggest, we move this repo to robotology, and I add it to superbuild  for HDE installation.

CC @traversaro  @DanielePucci  @lrapetti  @Yeshasvitvs  @claudia-lat

**Comment by DanielePucci** [comment]
Fine to me @kouroshD

**Comment by kouroshD** [comment]
@traversaro  Can you please move the repo to robotology, I do not have the permissions to do it. Thanks.

**Comment by traversaro** [comment]
Done.
