### ISSUE TITLE
Problem in using the model in Gazebo

### ISSUE THREAD

**Issue by vatsalkshah** [robotology-playground/human-gazebo#6]
The model falls from the sky when I spawn it and then bounces back and the breaks.
How should I fix this?
As mentioned, I have changed the values of masses and inertia of fake links to 0.0001 and 0.1 respectively. Should I change it to something else?
Also, what is the purpose of fake links?

**Comment by yeshasvitirupachuri** [comment]
@vatsalkshah I believe that the initial spawning position is not correct. 
Start gazebo in pause mode by using the argument `-u` e.g. `gazebo -u` and then check the initial position of the model. Alternatively, press space bar to pause gazebo and reset gazebo. This will show where the initial position of the model is.

**Comment by yeshasvitirupachuri** [comment]
> what is the purpose of fake links?

The purpose of the fake links are to create a spherical joint by combining 3 rotational joints together through the fake links.

**Comment by vatsalkshah** [comment]
@Yeshasvitvs  Still the problem persists. the model is spawning in the sky.
This is the repo where I have saved the edited file ( https://github.com/vatsalkshah/Edinburgh_summer/blob/master/human_urdf/urdf/human1.urdf ). Do I need to make any changes to it or the launch file?

**Comment by yeshasvitirupachuri** [comment]
@vatsalkshah please post a gif or a video link showing the behaviour

**Comment by vatsalkshah** [comment]
@Yeshasvitvs 
This is the video of the problem

![Screencast from 24-06-19 16_22_55](https://user-images.githubusercontent.com/31882705/60031871-66c92180-969d-11e9-9493-e29b251a6c8b.gif)

**Comment by yeshasvitirupachuri** [comment]
@vatsalkshah add `-u` in the `args` on line https://github.com/vatsalkshah/Edinburgh_summer/blob/master/human_urdf/launch/human.launch#L5

Moreover, note that the urdf doesn't have any control boards. This is the reason the model is exploding when you are trying to launch it with gazebo_ros package.

**Comment by vatsalkshah** [comment]
Thanks a lot. I'll implement the controller.
