### ISSUE TITLE
Fix LeftUpperLeg link visual and collision radius negative value to positive value

### ISSUE THREAD

**Issue by yeshasvitirupachuri** [robotology-playground/human-gazebo#8]
There is a bug in the auto-generation of the human urdf models. The `LeftUpperLeg` link visual radius value is negative for all the models:

https://github.com/robotology/human-gazebo/blob/f09f2c3eedc7415872988065071acedf30db60ae/humanSubject01/humanSubject01_66dof.urdf#L760

https://github.com/robotology/human-gazebo/blob/master/humanSubject01/humanSubject01_48dof.urdf#L663

https://github.com/robotology/human-gazebo/blob/f09f2c3eedc7415872988065071acedf30db60ae/humanSubject02/humanSubject02_66dof.urdf#L760

https://github.com/robotology/human-gazebo/blob/f09f2c3eedc7415872988065071acedf30db60ae/humanSubject02/humanSubject02_48dof.urdf#L655

https://github.com/robotology/human-gazebo/blob/f09f2c3eedc7415872988065071acedf30db60ae/humanSubject08/humanSubject08_66dof.urdf#L655

https://github.com/robotology/human-gazebo/blob/f09f2c3eedc7415872988065071acedf30db60ae/humanSubject08/humanSubject08_48dof.urdf#L655

@claudia-lat please fix this bug in the urdf autogeneration script

CC @lrapetti @kouroshD

**Comment by yeshasvitirupachuri** [comment]
This commit https://github.com/robotology/human-gazebo/commit/414d1ebbca168d43706ae9735bb47e89cfea582a fixes the current urdf files.

**Comment by claudia-lat** [comment]
The commit https://github.com/dic-iit/human-model-generator/commit/9074be743f178551bd4ad5c462df7ccb7aee6cc6 fixes the negative radius for the LeftUpperLeg cylinder.

 CC @Yeshasvitvs

**Comment by yeshasvitirupachuri** [comment]
Thanks @claudia-lat 
closing this issue
